/**
 * Generates public/sw.js with the full precache list (78 card images +
 * card back + brand assets) from src/data/cards.json.
 * Run: node scripts/generate-sw.js (re-run if the card set ever changes).
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const cards = JSON.parse(
  fs.readFileSync(path.join(root, "src", "data", "cards.json"), "utf8")
);

const images = cards.map((c) => c.image);
images.push("/cards/card-back.jpg");
images.push("/brand/logo.webp");
images.push("/icons/icon-192.webp");

const sw = `/* Sortes service worker — generated by scripts/generate-sw.js. Do not edit by hand. */
const VERSION = "sortes-v2";
const CARD_CACHE = "sortes-cards-v2";
const STATIC_CACHE = "sortes-static-v2";
const PRECACHE = ${JSON.stringify(images, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CARD_CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
      .catch(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith("sortes-") && k !== CARD_CACHE && k !== STATIC_CACHE)
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const hit = await cache.match(request);
  if (hit) return hit;
  const res = await fetch(request);
  if (res.ok) cache.put(request, res.clone());
  return res;
}

async function networkFirst(request) {
  const cache = await caches.open(STATIC_CACHE);
  try {
    const res = await fetch(request);
    if (res.ok) cache.put(request, res.clone());
    return res;
  } catch {
    const hit = await cache.match(request);
    if (hit) return hit;
    return cache.match("/offline");
  }
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Card images + brand assets: cache-first (offline readings need these).
  if (
    url.pathname.startsWith("/cards/") ||
    url.pathname.startsWith("/brand/") ||
    url.pathname.startsWith("/icons/")
  ) {
    event.respondWith(cacheFirst(request, CARD_CACHE));
    return;
  }
  // App bundles: cache-first so visited pages render offline.
  if (url.pathname.startsWith("/_next/static/")) {
    event.respondWith(cacheFirst(request, STATIC_CACHE));
    return;
  }
  // Page navigations: network-first with offline fallback page.
  if (request.mode === "navigate") {
    event.respondWith(networkFirst(request));
  }
});
`;

fs.writeFileSync(path.join(root, "public", "sw.js"), sw);
console.log(`Wrote public/sw.js with ${images.length} precached assets.`);
