import { APP_NAME, APP_SHORT, CONTACT_EMAIL, SITE_URL } from "@/lib/site";

export const metadata = {
  title: "Privacy Policy",
  description: `How ${APP_SHORT} collects, uses, and deletes your data.`,
};

const UPDATED = "September 29, 2026";

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <p className="text-xs uppercase tracking-[0.35em] text-gold">Legal</p>
      <h1 className="mt-3 font-display text-5xl text-goldbright">Privacy Policy</h1>
      <p className="mt-2 text-sm text-mist">Last updated: {UPDATED}</p>

      <div className="mt-8 space-y-8 text-[15px] leading-relaxed text-cream/85">
        <section>
          <h2 className="font-display text-2xl text-goldbright">1. What Sortes is</h2>
          <p className="mt-2">
            {APP_NAME} ({SITE_URL.replace("https://", "")}) is a tarot reading
            web app. Readings are offered for <strong>reflection and
            perspective only</strong>; they are never guaranteed predictions
            about the future.
          </p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-goldbright">2. Data we collect</h2>
          <ul className="mt-2 list-disc space-y-2 pl-5">
            <li>
              <strong>Account data:</strong> if you create an account, your
              email address and credit balance.
            </li>
            <li>
              <strong>Purchase data:</strong> for every transaction we store
              your email, the pack type, the amount, and the date.
            </li>
            <li>
              <strong>Reading intake:</strong> for personalized readings you
              may share a first name, a category, your story, and one question.
              <strong> Raw intake form data is automatically deleted after 30
              days.</strong> The generated reading itself is kept so you can
              revisit it in your journal.
            </li>
            <li>
              <strong>On-device data:</strong> for guests, daily cards, credit
              balance, and reading history are stored in your browser&apos;s
              local storage and never leave your device until you create an
              account.
            </li>
            <li>
              <strong>Analytics:</strong> we use privacy-friendly analytics
              (Plausible) that records page views, reading starts, and
              completed purchases without cookies or cross-site tracking.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-2xl text-goldbright">3. What we send to the AI provider</h2>
          <p className="mt-2">
            Personalized readings are generated by an AI provider (via
            OpenRouter). We send <strong>only your first name and the
            essentials of your story and question</strong>. We never send full
            birthdays, surnames, or contact details to the model. The provider
            processes the prompt to generate your reading and does not use it
            to identify you.
          </p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-goldbright">4. Health readings</h2>
          <p className="mt-2">
            Readings in the Health and Wellness category are{" "}
            <strong>general wellness reflection only. They never diagnose,
            treat, or predict medical outcomes</strong> and cannot replace a
            licensed professional. If you have a health concern, please speak
            with a qualified clinician.
          </p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-goldbright">5. Data retention and deletion</h2>
          <ul className="mt-2 list-disc space-y-2 pl-5">
            <li>Raw intake form data: deleted automatically after 30 days.</li>
            <li>Generated readings: kept until you delete them or your account.</li>
            <li>Purchase records: kept as required for accounting and tax law.</li>
            <li>
              You may request export or deletion of your data at any time by
              emailing {CONTACT_EMAIL}.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-2xl text-goldbright">6. Children</h2>
          <p className="mt-2">
            {APP_SHORT} is not directed at children under 13, and we do not
            knowingly collect their data.
          </p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-goldbright">7. Contact</h2>
          <p className="mt-2">
            Questions about this policy:{" "}
            <a className="text-goldbright underline" href={`mailto:${CONTACT_EMAIL}`}>
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
